# Prometheus scrapes metrics exposed by the OTel Collector (Prometheus exporter).
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

